### ISSUE TITLE
Add minimum step size property to adjustable objects (Like sliders)

### ISSUE THREAD

**Issue by jostie123** [HASwitchPlate/openHASP#211]
**Is your feature request related to a problem? Please describe.**
if you have big fingers like me setting a exact number is difficult with steps this would be easier.

**Describe the solution you'd like**
a settable property for adjustable objects so you can set steps between min and max.

i am setting set-points for my lights inside HA to input_number sensors these have this minimum step size (5) but openhasp ignores them and sets numbers of 1

**Comment by fvanroie** [comment]
LVGL doesn't have a step parameter for sliders, but I think the same result can be achieved by multiplying / dividing the value by 5.

See the [Thermostat example](https://haswitchplate.github.io/openHASP-docs/0.6.1/integrations/home-assistant/sampl_conf/#generic-thermostatclimate) where this method is used to get `0.1` increments instead of `1`. You could use the same logic to increase the increments to `5` in your application.
